### ISSUE TITLE
F值计算

### ISSUE THREAD

**Issue by SjiYang** [nju-websoft/GLRE#1]
您好，阅读了下您的代码，但没有找到计算Inter-F和Intra-F的代码的位置
可以提供下计算这两个数值的代码和方法吗
谢谢！

**Comment by slzbywdf** [comment]
你好，这部分代码在trainer.py 的471-475行 ，self.test_prune_recall['0-1']对应intra-F的结果，self.test_prune_recall['1-max']对应inter-F的结果。 这边的“0-1” “1-max”指的是实体对之间句子的距离

**Comment by SjiYang** [comment]
感谢回复! 我再研究下

**Comment by yyzhuang1991** [comment]
请问你有intra-F1 和inter-F1的具体数值吗？
