### ISSUE TITLE
关于计算资源

### ISSUE THREAD

**Issue by chenhaishun** [nju-websoft/GLRE#3]
你好，感谢你出色的尝试工作！
请问一下您的实验中所用到的GPU数量以及时间消耗是多少呢？
期待你的回复！

**Comment by slzbywdf** [comment]
我用的 NVIDIA Tesla V100，显存32G. 对于DocRED数据集，batch_size=8时， GLRE（Bert_base）大约44轮收敛，每轮8分钟左右（训练集+验证集）。

**Comment by chenhaishun** [comment]
谢谢你的回复，感谢！
